---
title: "Datapalooza Report"
author: "Kristin Schmidt"
date: "November 22, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

"The Data Science Institute (DSI) at the University of Virginia stands at the forefront of the field of data science by educating data scientists, undertaking leading-edge research and collaborating with private and government sectors as part of a virtuous cycle to take us into a better, brighter future. The mission of the Data Science Institute is to achieve excellence in data-driven research and education through solving important problems and providing the workforce of tomorrow. We are an institute that crosses disciplines, departments, schools and colleges to leverage UVA's combined capabilities in data science. We create meaningful public/private partnerships and foster innovation." From the DSI website.

These are exactly the values and key pieces that came across on Friday's Datapalooza event. By highlighting research in the UVa community, and by showcasing the top speakers and what problems are being solved, Datapalooza reached the audience in a way that is true to their mission. The event was carried on a platform that received input from the audience, in that everyone received a code on their nametag with which we could enter on a website with whom we are talking. The point of this was to form a collaborative map between all people represented at this event. For example, when I spoke to the director of clinical research during one of the networking breaks, I put in her code into a website and a link between "undergraduate" and "department representative" was created. On the big screen in the theatre, a gigantic map formed that was color coded by all representative groups and a line between all the people they talked to: A very chatty group! This was another interesting touch on how the institute values interdisciplinary networking and depicted how much they love data. Throughout the event, they have truly captured their capabilities and values, which was fascinating.
	
The event started out with a greeting from Dr. Phil Bourne, as he described to us how excited he is about the fourth data science paradigm that is upon us. He explained that the first paradigm was about 2000 years ago, when people where just observing. During the second paradigm, people started to model - started to experiment with physics. The third paradigm is computational, and the fourth paradigm - the one upon us - is data driven and that we are leveraging observations for the benefit of society.

The fireside chat between Dr. Bourne and James Ryan was a very interesting talk, as they discussed the intersection of data science with the university. They described UVa as a data driven institution with the purpose to serve others, and went on to describe data science as a network that cuts through all of the hierarchical structures at the university; data science is cross- disciplinary and uni-collaborational. As such, Ryan suggests that we must organize differently. Starting with K-12, we must stress the importance of data. Data must be open and shared in research - essentially forming new business models between private companies and Universities, to come up with a transparent purpose that is sustainable. But what are the obstacles to openness? The mindset of people, which is why we need a social change. At this point, pharmaceutical companies use replications of each other's work, while print journals have a monopoly. There are still a lot of ethical questions that are unanswered. Print journals are not the key to the future - we must find a way to keep data available and form a type of literacy starting at the undergraduate level. We must use data in the right way, which means we must learn to ask the right questions. Both Dr. Bourne and President Ryan closed the talk by restating the mission of the DSI - which is to find interesting questions!

The research highlight section I chose was on machine learning. I have only recently (mid-semester) really understood machine learning, so I thought it was interesting to go to this section. The first presenter was Professor Kristen Naegle, with the topic: Openensembles: Ensemble Clustering in Python. Her talk was describing clustering as an unsupervised learning technique, specifically how clustering reduces data dimensions and how it uses unsupervised data recognition. Ensemble clustering is repeated clustering with perturbation. We can perturbate in the following ways: We can add noise to see how robust data is, we can project into n dimensions to bypass excess dimensions, and we can change K to optimize the model. We could also vary starting points, global extremes, or change multiple parameters to answer multiple questions. To finish, algorithms can assemble results across the ensemble and produce one clustering result. This gives a connectivity as opposed to a cluster only.

The second presenter was Katja Gilbo, also from the BME department. Her work was on the development of tools to help diagnose hypertrophic cardiomyopathy (HCM). Her job is to find biomarkers associated with HCM for better diagnostic in the long term. Together with Oxford University, she is using machine learning to train a system to label MRI images of the heart septum. Current methods only look at a few measures to diagnose HCM, while her algorithm will look at six different labels. At this point, she describes that data preprocessing takes a lot of filtering, and that she uses pretrained neural net, pretrained and linear classifiers, or she trains the system completely from scratch. Katja's talk was complicated, but interesting! I appreciate that there are efforts to help doctors diagnose hard to detect diseases.

Probably the most unmotivated speaker of the four research highlights was Samarth Singh from the Department of Engineering Systems and Environment. His talk was about plagiarism detection, using semantic analysis. He described that there are lots of outdated techniques that are too simple to detect plagiarism - like word for word matching. Instead, he explained that automatic classification (grouping with existing documents on same topic) is the key to plagiarism detection. The technical term for this is back-end clustering. It allows thorough processing and analysis of documents and texts without having to compare it to every document in the database. The analysis is grammar based (semantic), using object-action pairs to cluster and compare with a database. The current pitfalls are small datasets, and a cross-language barrier as there would be no training data. I was not very impressed by this talk, probably due to the presenter. He was very monotone, and not excited.
	
The last talk was probably the most entertaining. Madhur Behl, from the Department of Computer Science and Engineering Systems and Environment (LINK LAB), spoke about teaching autonomous vehicles to handle edge cases in traffic. Deep Racing AI! Many factors are in play in autonomous driving: the vehicle needs to know where it is at, understand its surroundings, plan its trajectory, and interact with other components (driver). A big research question for Professor Behl and his lab is: "how do we ensure safety?" There are two options for training the AI. We could use brute force, by providing enough training data to present edge cases, or formal reasoning. In his lab, they teach AI by autonomously racing vehicles both physically or with computer simulations. This provides many edge case scenarios, from which AI can learn. The result is an AI that can predict trajectories in a way that matches how real race car drivers navigate the track, despite speed and proximity of other vehicles. The talk was entertaining in that he showed racing footage, and seemed to generally be extremely excited about his projects.

The tech talk of the event was presented by Miriam Friedel from Metis Machine, and Priscilla Alexander from Capital One. Both talks were not inspirational, and seemed to be more business oriented (as opposed to research). The tech talks were essentially talking about how data can be processed by these two companies, to create value for their clients. Metis machine makes a machine learning platform to streamline integration of predictive models into businesses. Miriam presented a summary of the pipeline of this integration in general terms, so that the particular strengths of their product could be explained. Priscilla from Capital One presented seven lessons that she learned from gathering and building teams that use ML. She emphasizes in these 7 lessons that a team must be focused on core questions being asked and efficiency with which they are answered. The talk was also geared more toward companies, in that she concentrated on communication and investment. One of her seven lessons was literally: "If you don't have the data, you don't have the data." It was not a very revolutionary and sensational talk, but did bring across one important point: We must have interdisciplinary teams. This results in the best marketing opportunities.

The keynote speech was given by Robin Thottungal. The talk seemed somewhat disjointed, but spoke to the audience in an emotional way. As a former chief data scientist for the Environmental Protection Agency, Robin brought many examples of data visualization to light. He connected data science to issues that the world is facing due to climate change and poor interconnection of people and organizations. It is his belief that we can transform policy making with data science, since it illuminates the complexities of global issues. He also touched on the common pitfalls of AI, especially related to racial bias in criminal justice (fascinating!). He finished his talk with the topic of the workforce realignment, that must take place in order to account for increasing automation, and the changing climate. The overarching message was that the country needs to begin open discussions about major issues, preferably informed by data visualization. The examples he presented were very moving, but the application and relevance of all these independent cases was not clear. His final conclusion was that instead of STEM fields, we need STEAM fields, including the arts (he is currently chief technology officer at the national gallery of arts). He believes that data scientists must be more empathetic, in order to make their work applicable to a just society. His talk was lacking organizational structure, but clearly had grand intentions. 

The entire event was interesting, and I appreciated what people are thinking about. It encourages me when I hear that there are individuals that change the world, to make it better, one septum image or one race car at a time. I wished I was given the opportunity to visit a different research highlight talk instead of the tech talk, but was overall impressed with the production of the event as a whole. In conclusion, it was nice to learn how big data is actually relevant to our future, and I could draw a connection to Dr. Bourne's comment on us approaching a fourth paradigm.




